#!/usr/bin/ruby
# read feature file and :

def loop(scenes, scen_list, feat)
  run = true
  idx = 0
  failures = []
  passed = []
  while run
    puts 'n(ext)|p(rev)|q(uit)|s(tatus)|r(un)'
    #input = gets
    input = $stdin.gets.chomp
    case input
    when 'n'
      idx += 1
      puts "Going forward one scenario: idx now #{idx}"
      puts "Now at: #{scenes[idx]}"
    when 'p'
      idx -= 1
      puts "Going back one scenario: idx now #{idx}"
      puts "Now at: #{scenes[idx]}"
    when 'q'
      puts 'Quitting...'
      run = false
    when 's'
      # idx + 1 to offset array  start
      puts "Status: #{idx + 1}/#{scenes.length} | Passed: #{passed.length} | Failed: #{failures.length} | Total: #{scen_list.length}"
    when 'r'
      puts "Running #{scenes[idx]}"
      puts "cmd is cucumber #{feat}:#{scen_list[idx]}"
      system("cucumber #{feat}:#{scen_list[idx]}")
    else
      puts 'unknown command'
    end
  end
end

feat = ARGV[0]
# List of line numbers that senarios are on
scen_list = []
# start at 1 as cucumber starts with 1
counter = 1

scenes = []
File.open(feat, 'r') do |file|
  while line = file.gets
    if line.include?('Scenario') && !line.include?('#')
      scen_list.push(counter)
      scenes.push(line.chomp)
    end
    counter += 1
  end
end

puts feat
puts scen_list
puts scenes

loop(scenes, scen_list, feat)
