#!/usr/bin/ruby
# cucumber-shortcake
# Martin Seidl - mseidl@suse.de
# Under the MLLLULW license - Mega-Lesser-Lesser-Lesser-Ultra-Lesser-Whatever.
require 'optparse'

options = {}
# Default run set
def_run_set = 'run_sets/testsuite.yml'

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"
  opts.on('-r', '--runset RUNSET', 'Runset, default is run_sets/testsuite.yml') { |x| options[:runset] = x }
  opts.on('-m', '--match MATCH', 'Feature file or string to search for') { |x| options[:match] = x }
  opts.on('-i', '--include', 'Include feature') { |x| options[:include] = true if x }
end.parse!

if !options[:runset]
  options[:runset] = def_run_set
end

features = []

File.open(options[:runset], 'r') do |file|
  catch :done do
    while line = file.gets
      line.gsub!('- ', '').chomp!
      if !line.include? '#'
        if line.include? options[:match] 
          features.push(line) if options[:include]
          throw :done
        end
        features.push(line)
      end
    end
  end
end

# exec exits the ruby program and replaces it with a shell call to cucumber
cmd = "cucumber " + features.join(' ')
#puts "Now executing #{cmd}"
exec(cmd)
